my-kv-db {
  metrics-port: 9091
  metrics-enabled: true
  db-conf: {
    server: {
      type = "http"
      host: "0.0.0.0"
      port: 9000
      max-connections: 1024
      idle-timeout: 60.seconds
    }
    engine: {
      root-dir: "/catalog"
      file-write-parallelism: 10
      file-write-buffer-size: 10000
      max-segment-size: 10240
      max-segment-count: 10
      max-retries: 3
      failure-recovery: true
    }
  }
}
