datastax-java-driver.advanced.metrics {
  factory.class = DropwizardMetricsFactory
  session.enabled = [connected-nodes, cql-requests]
  node.enabled = [pool.open-connections, pool.in-flight]
}

datastax-java-driver.advanced.netty.io-group {
  size = 0
}

datastax-java-driver.basic.request {
  timeout = 900 milliseconds
  timeout = ${?SCYLLA_REQUEST_TIMEOUT}
  consistency = LOCAL_ONE
}
cc-api-app {

  metrics-port = 9091
  metrics-port = ${?METRICS_PORT}
  metrics-enabled = true
  metrics-enabled = ${?METRICS_ENABLED}
  connections {
    scylla {
      contact-points = "172.16.6.24,172.16.6.28,172.16.6.12,172.16.6.6"
      contact-points = ${?SCYLLA_CONTACT_POINTS}
      port = 9042
      port = ${?SCYLLA_PORT}
      local-datacenter = "Selectel"
      local-datacenter = ${?SCYLLA_LOCAL_DC}
      user = "null"
      user = ${?SCYLLA_USER}
      pwd = "null"
      pwd = ${?SCYLLA_PWD}
      timeouts {
        migration-timeout = 5 seconds
      }
    }
    admin-db {
      postgresAddress = "localhost"
      postgresAddress = ${?PG_ADDRESS}
      postgresPort = 5000
      postgresPort = ${?PG_PORT}
      postgresDb = "cc-api"
      postgresDb = ${?ADMIN_DB_NAME}
      url = "jdbc:postgresql://"${cc-api-app.connections.admin-db.postgresAddress}":"${cc-api-app.connections.admin-db.postgresPort}"/"${cc-api-app.connections.admin-db.postgresDb}
      user = "postgres"
      user = ${?ADMIN_DB_USER}
      password = "postgres"
      password = ${?ADMIN_DB_PASSWORD}
      schema = "public"
      migration-dirs = "pg.migration"
      migration-dirs = ${?ADMIN_DB_MIGRATION_DIRS}
      baseline-on-migrate = false
      schema-hist-table = "schema_version"
    }
  }

  api-http-endpoint {
    host = 0.0.0.0
    port = 9000
    max-connections = 1024
    max-connections = ${?MAX_CONNECTIONS}
    idle-timeout = 60 seconds
    idle-timeout = ${?IDLE_TIMEOUT}
  }

  admin-db-enabled = false
  admin-db-enabled = ${?ADMIN_DB_ENABLED}

  auth {
    creds-data = ""
    creds-data = ${?AUTH_CREDS_DATA}
    db-creds = {
      conn = ${cc-api-app.connections.admin-db}
      refresh-interval = 1 minute
    }
  }

  feature-reading {
    conn = ${cc-api-app.connections.scylla}
    keyspace = "customer_catalog"
    keyspace = ${?SCYLLA_KEYSPACE}
    table-switch = {
      check-interval = 1 minute
    }
  }

  feature-spec-reading {
    location = "jar://customer_profile_spec.json"
    location = ${?FEATURE_SPEC_LOCATION}
    refresh-interval = 1 minute
  }

  non-obfuscated-logins = "ui;test"
  non-obfuscated-logins = ${?NON_OBFUSCATED_LOGINS}

  logging {
    warn-latency-threshold = 5000
    warn-latency-threshold = ${?WARN_LATENCY_THRESHOLD}
  }

}
